### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jonl1096** [jonl1096/MultimodalDeepLearning-PerformancePrediction#1]
# TODO

### General
- get more data
  - Twitter: increase time range and perhaps # tweets per day
  - Articles: pull more articles
- investigate more complicated preprocessing methods like using syntactic structure and stuff
    - library Jered is using for his research with dredze, has a really nice syntax parser specifically for tweets

@alexahn917 

@jonl1096

@dmcinerney 

# COMPLETED

@alexahn917 
- Scrape Twitter data from 14 ~ 16
- Run LDA on each year
- Store 600 x num_topics data to csv

// python Exporter.py --querysearch "orioles" --since 2016-02-28 --until 2016-10-02
// python Exporter.py --querysearch "orioles" --since 2015-03-01 --until 2015-10-04
// python Exporter.py --querysearch "orioles" --since 2014-02-28 --until 2014-10-15

- Implement RNN

@jonl1096
- [x] Implement basic deep autoencoder
    - [implementation](https://github.com/jonl1096/d2m-final-project/blob/master/autoencoder/testing/Deep%20Autoencoder.ipynb)
    - [documentation](https://blog.keras.io/building-autoencoders-in-keras.html)

@dmcinerney 
- [x] Implement convolutional autoencoder found [here](https://blog.keras.io/building-autoencoders-in-keras.html)
    - and possibly see how it compares to the deep autoencoder
- [x] modify autoencoders to work on our data
- [x] work autoencoders into a boltzman machine to generate a joint representation
    - might need some help with this
